import { NasaSearchResult } from "../service/NasaImagesApi";

export default [
  {
    nasaId: "sts059-s-027",
    title: "False-color composite image of Raco, Michigan",
    date: "1994-04-10T00:00:00Z",
    center: "JSC",
    description:
      "STS059-S-027 (10 April 1994) --- This image is a false-color composite of Raco, Michigan, centered at 46.39 degrees north latitude, 84.88 degrees east longitude.  This image was acquired by the Spaceborne Imaging Radar-C and X-Band Synthetic Aperture Radar (SIR-C/X-SAR) aboard the Space Shuttle Endeavour on its 6th orbit and during the first full-capacity test of the instrument.  This image was produced using both L-Band and C-Band data.  The area shown is approximately 20 kilometers by 50 kilometers.  Raco is located at the eastern end of Michigan's upper peninsula, west of Sault Ste. Marie and south of Whitefish Bay on Lake Superior.  The site is located at the boundary between the boreal forests and the northern temperate forests, a transitional zone that is expected to be ecologically sensitive to anticipated global changes resulting from climatic warming.  On any given day, there is a 60 percent chance that this area will be obscured to some extent by cloud cover which makes it difficult to image using optical sensors.  In this color representation (Red=LHH, Green=LHV, Blue=CHH), darker areas in the image are smooth surfaces such as frozen lakes and other non-forested areas.  The colors are related to the types of trees and the brightness is related to the amount of plant material covering the surface, called forest biomass.  Accurate information about land-cover is important to area resource managers and for use in regional- to global-scale scientific models used to understand global change.  SIR-C/X-SAR radars illuminate Earth with microwaves allowing detailed observations at any time, regardless of weather or sunlight conditions.  SIR-C/X-SAR uses three microwave wavelengths: L-Band (24 cm), C-Band (6 cm), and X-Band (3 cm).  The multi-frequency data will be used by the international scientific community to better understand the global environment and how it is changing.  The SIR-C/X-SAR data, complemented by aircraft and ground studies, will give scientists clearer insights into those environmental changes which are caused by nature and those changes which are induced by human activity.  SIR-C was developed by NASA's Jet Propulsion Laboratory (JPL).  X-SAR was developed by the Dornire and Alenia Spazio Companies for the German Space Agency, Deutsche Agentur fuer Raumfahrtangelegenheiten (DARA), and the Italian Space Agency, Agenzia Spaziale Italiana (ASI).    JPL Photo ID: P-43882",
    thumb:
      "https://images-assets.nasa.gov/image/sts059-s-027/sts059-s-027~thumb.jpg",
  },
  {
    nasaId: "PIA17312",
    title: "Kirkenes, Norway",
    date: "2013-07-09T16:00:00Z",
    center: "JPL",
    description:
      "This image from NASA Terra spacecraft shows the town of Kirkenes in northernmost Norway, with its 3400 inhabitants, as they prepare for an expected boom as a shipping hub, as global warming has led to the opening up of the Northern Sea Route.",
    thumb: "https://images-assets.nasa.gov/image/PIA17312/PIA17312~thumb.jpg",
  },
  {
    nasaId: "iss036e028913",
    title: "sunset",
    date: "2013-08-04T00:00:00Z",
    center: "JSC",
    description:
      "ISS036-E-028913 (4 Aug. 2013) --- A sunset over the Aleutian Islands, with noctilucent clouds, is featured in this image photographed by an Expedition 36 crew member on the International Space Station. The crew member took this panoramic view looking north from the Aleutian Islands when the space station was flying east at ?the top of the orbit,? the northernmost latitude reached by the orbital complex (51.6 degrees north). If the sun had been higher, the string of Aleutian Islands would have been visible in the foreground. Here the islands are on the dark side of the day-night line. From their vantage point at 222 kilometers altitude on this day, crew members were able to see as far north as the Arctic Ocean and the midnight sun. This image was taken just 20 minutes after local midnight in early August 2013. The midnight sun makes the red, diamond-shaped teardrop reflection (lower center)?perhaps a reflection within the camera lens, or from the window frame, or some item inside the ISS. Long blue-white stringers can be seen in the atmosphere above the midnight sun. These are known as noctilucent clouds (night-shining clouds). Some crew members say these wispy, rippling, iridescent clouds are the most beautiful phenomena they see from orbit. Noctilucents are thin so that they are best seen after sunset when the viewer is on the night side of the day-night line, but while these high clouds are still lit by the sun. Crews are trained in this somewhat complicated geometry?of clouds being lit from beneath, with the spacecraft in sunlight though the ground directly beneath is in darkness. Noctilucent clouds are also known as polar mesospheric clouds (PMCs) as they appear in the summer hemisphere over polar latitudes. Some data suggest that they are becoming brighter, and appearing at lower latitudes, perhaps as an effect of global warming.  A comparison of noctilucent cloud formation from 2012 and 2013 has been compiled using data from NASA?s Aeronomy of Ice in the Mesosphere (AIM) shows an earlier start and an increase in the area covered by these clouds in 2013. Polar mesospheric clouds are interesting to scientists because they form much higher in the atmosphere (75-90 kilometers) compared with altitudes of normal rainclouds that form in the lowest, densest ?weather-layer? below approximately 15 kilometers. The weather layer, or troposphere, is most distinct in this image as a thin orange line along the left horizon.",
    thumb:
      "https://images-assets.nasa.gov/image/iss036e028913/iss036e028913~thumb.jpg",
  },
  {
    nasaId: "PIA23514",
    title: "A Water Ice Map for Mars",
    date: "2019-12-10T00:00:00Z",
    center: "JPL",
    description:
      "This rainbow-colored map shows underground water ice on Mars. Cool colors represent less than one foot (30 centimeters) below the surface; warm colors are over two feet (60 centimeters) deep. Sprawling black zones on the map represent areas where a landing spacecraft would sink into fine dust. The outlined box represents the ideal region to send astronauts for them to be able to dig up water ice.      The map was created by combining data from multiple NASA orbiters, including the Mars Reconnaissance Orbiter and its Mars Climate Sounder instrument; Mars Odyssey and its Thermal Emission Imaging System; and the Mars Global Surveyor.  https://photojournal.jpl.nasa.gov/catalog/PIA23514",
    thumb: "https://images-assets.nasa.gov/image/PIA23514/PIA23514~thumb.jpg",
  },
  {
    nasaId: "0300805",
    title: "Space Science",
    date: "2001-09-30T00:00:00Z",
    center: "MSFC",
    description:
      "Absorption of solar energy heats up our planet's surface and atmosphere making life for us possible. But the energy carnot stay bound up in the Earth's environment forever. If it did, the Earth would be as hot as the sun. Instead, as the surface and atmosphere warm, they emit thermal long wave radiation, some of which escapes into space and allows the Earth to cool. This false color image of the Earth was produced by the Clouds and the Earth's Radiant Energy System (CERES) instrument flying aboard NASA's Terra spacecraft. The image shows where more or less heat, in the form of long-wave radiation, is emanating from the top of the Earth's atmosphere. As one can see in the image, the thermal radiation leaving the oceans is fairly uniform. The blue swaths represent thick clouds, the tops of which are so high they are among the coldest places on Earth. In the American Southwest, which can be seen in the upper right hand corner of the globe, there is often little cloud cover to block outgoing radiation and relatively little water to absorb solar energy making the amount of outgoing radiation in this area exceeding that of the oceans. Recently, NASA researchers discovered that incoming solar radiation and outgoing thermal radiation increased in the tropics from the 1980s to the 1990s. They believe the unexpected change has to do with apparent change in circulation patterns around the globe, which effectively reduce the amount of water vapor and cloud cover in the upper reaches of the atmosphere. Without the clouds, more sunlight was allowed to enter the tropical zones and more thermal energy was allowed to leave. The findings may have big implications for climate change and future global warming. (Image courtesy NASA Goddard)",
    thumb: "https://images-assets.nasa.gov/image/0300805/0300805~thumb.jpg",
  },
  {
    nasaId: "PIA26100",
    title: "SWOT's Detailed View of Global Sea Level",
    date: "2023-10-30T00:00:00Z",
    center: "JPL",
    description:
      "This animation shows global sea level data collected by the Surface Water and Ocean Topography (SWOT) satellite during its first 21-day science orbit, which it completed from July 26 to Aug. 16, 2023.  Red and orange indicate ocean heights that were higher than the global mean sea surface height, while blue represents lower-than-the mean. Sea level differences can highlight ocean currents, like the Gulf Stream coming off the U.S. East Coast or the Kuroshio current off the east coast of Japan. Increased sea surface heights can also indicate regions of relatively warmer water – like the eastern part of the equatorial Pacific Ocean during an El Niño – because water expands as it warms.  The SWOT science team made the measurements using the spacecraft's Ka-band Radar Interferometer (KaRIn) instrument. With two antennas spread 33 feet (10 meters) apart on a boom, KaRIn produces a pair of data swaths (tracks visible in the animation) as it circles the globe, bouncing radar pulses off the water's surface to collect surface-height measurements.  Launched on Dec. 16, 2022, from Vandenberg Space Force Base in central California, SWOT is now in its operations phase, measuring the height of nearly all water on Earth's surface. The satellite will provide one of the most detailed, comprehensive views yet of the planet's oceans and fresh water lakes and rivers, collecting data that will be used for research and other purposes.  Animation available at https://photojournal.jpl.nasa.gov/catalog/PIA26100",
    thumb: "https://images-assets.nasa.gov/image/PIA26100/PIA26100~thumb.jpg",
  },
  {
    nasaId: "PIA01737",
    title: "Space Radar Image of Weddell Sea, Antarctica",
    date: "1999-05-01T21:33:59Z",
    center: "JPL",
    description:
      "This Spaceborne Imaging Radar-C/X-band Synthetic Aperture Radar color composite shows a portion of the Weddell Sea, which is adjacent to the continent of Antarctica. The image shows extensive coverage of first-year sea ice mixtures and patches of open water inside the ice margin. The image covers a 100 kilometer by 30 kilometer (62 mile by 18.5 mile) region of the southern ocean, centered at approximately 57 degrees south latitude and 3 degrees east longitude, which was acquired on October 3, 1994. Data used to create this image were obtained using the L-band (horizontally transmitted and vertically received) in red; the L-band (horizontally transmitted and received) in green; and the C-band (horizontally transmitted and received) in blue.  The sea ice, which appears rust-brown in the image, is composed of loosely packed floes from approximately 1 meter to 2 meters (3 feet to 6.5 feet) thick and ranging from 1 meter to 20 meters (3 feet to 65.5 feet) in diameter. Large patches of open water, shown as turquoise blue, are scattered throughout the area, which is typical for ice margins experiencing off-ice winds. The thin, well-organized lines clearly visible in the ice pack are caused by radar energy reflected by floes riding the crest of ocean swells. The wispy, black features seen throughout the image represent areas where new ice is forming. Sea ice, because it acts as an insulator, reduces the loss of heat between the relatively warm ocean and cold atmosphere. This interaction is an important component of the global climate system. Because of the unique combination of winds, currents and temperatures found in this region, ice can extend many hundreds of kilometers north of Antarctica each winter, which classifies the Weddell Sea as one of nature's greatest ice-making engines. During the formation of sea ice, great quantities of salt are expelled from the frozen water. The salt increases the density of the upper layer of sea water, which then sinks to great depths. Oceanographers believe this process forms most of the oceans' deep water. Sea ice covering all of the southern oceans, including the Weddell Sea, typically reaches its most northerly extent in about September. As periods of daylight become gradually longer in the Southern Hemisphere, ice formation stops and the ice edge retreats southward. By February, most of the sea ice surrounding Antarctica disappears. Imaging radar is extremely useful for studying the polar regions because of the long periods of darkness and extensive cloud cover. The multiple frequencies of the SIR-C/X-SAR instruments allow further study into ways of improving the separation of the various thickness ranges of sea ice, which are vital to understanding the heat balance in the ice, ocean and atmospheric system.  http://photojournal.jpl.nasa.gov/catalog/PIA01737",
    thumb: "https://images-assets.nasa.gov/image/PIA01737/PIA01737~thumb.jpg",
  },
  {
    nasaId: "GSFC_20171208_Archive_e000638",
    title: "Warming Seas and Melting Ice Sheets",
    date: "2017-12-08T00:00:00Z",
    center: "GSFC",
    description:
      'Sea level rise is a natural consequence of the warming of our planet.  We know this from basic physics. When water heats up, it expands. So when the ocean warms, sea level rises. When ice is exposed to heat, it melts. And when ice on land melts and water runs into the ocean, sea level rises.  For thousands of years, sea level has remained relatively stable and human communities have settled along the planet’s coastlines. But now Earth’s seas are rising. Globally, sea level has risen about eight inches since the beginning of the 20th century and more than two inches in the last 20 years alone.  All signs suggest that this rise is accelerating.  Read more: <a href="http://go.nasa.gov/1heZn29" rel="nofollow">go.nasa.gov/1heZn29</a>  Caption: An iceberg floats in Disko Bay, near Ilulissat, Greenland, on July 24, 2015. The massive Greenland ice sheet is shedding about 300 gigatons of ice a year into the ocean, making it the single largest source of sea level rise from melting ice.  Credits: NASA/Saskia Madlener  <b><a href="http://www.nasa.gov/audience/formedia/features/MP_Photo_Guidelines.html" rel="nofollow">NASA image use policy.</a></b>  <b><a href="http://www.nasa.gov/centers/goddard/home/index.html" rel="nofollow">NASA Goddard Space Flight Center</a></b> enables NASA’s mission through four scientific endeavors: Earth Science, Heliophysics, Solar System Exploration, and Astrophysics. Goddard plays a leading role in NASA’s accomplishments by contributing compelling scientific knowledge to advance the Agency’s mission.  <b>Follow us on <a href="http://twitter.com/NASAGoddardPix" rel="nofollow">Twitter</a></b>  <b>Like us on <a href="http://www.facebook.com/pages/Greenbelt-MD/NASA-Goddard/395013845897?ref=tsd" rel="nofollow">Facebook</a></b>  <b>Find us on <a href="http://instagrid.me/nasagoddard/?vm=grid" rel="nofollow">Instagram</a></b>',
    thumb:
      "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e000638/GSFC_20171208_Archive_e000638~thumb.jpg",
  },
  {
    nasaId: "PIA02300",
    title: 'Defrosting Polar Dunes--"They Look Like Bushes!"',
    date: "2000-05-26T00:00:00Z",
    center: "JPL",
    description:
      '"They look like bushes!" That\'s what almost everyone says when they see the dark features found in pictures taken of sand dunes in the polar regions as they are beginning to defrost after a long, cold winter. It is hard to escape the fact that, at first glance, these images acquired by the Mars Global Surveyor (MGS) Mars Orbiter Camera (MOC) over both polar regions during the spring and summer seasons, do indeed resemble aerial photographs of sand dune fields on Earth -- complete with vegetation growing on and around them! Of course, this is not what the features are, as we describe below and in related picture captions. Still, don\'t they look like vegetation to you? Shown here are two views of the same MGS MOC image. On the left is the full scene, on the right is an expanded view of a portion of the scene on the left. The bright, smooth surfaces that are dotted with occasional, nearly triangular dark spots are sand dunes covered by winter frost.  The MGS MOC has been used over the past several months (April-August 1999) to monitor dark spots as they form and evolve on polar dune surfaces. The dark spots typically appear first along the lower margins of a dune -- similar to the position of bushes and tufts of grass that occur in and among some sand dunes on Earth.  Because the martian air pressure is very low -- 100 times lower than at Sea Level on Earth -- ice on Mars does not melt and become liquid when it warms up. Instead, ice sublimes -- that is, it changes directly from solid to gas, just as "dry ice" does on Earth. As polar dunes emerge from the months-long winter night, and first become exposed to sunlight, the bright winter frost and snow begins to sublime. This process is not uniform everywhere on a dune, but begins in small spots and then over several months it spreads until the entire dune is spotted like a leopard.  The early stages of the defrosting process -- as in the picture shown here -- give the impression that something is "growing" on the dunes. The sand underneath the frost is dark, just like basalt beach sand in Hawaii. Once it is exposed to sunlight, the dark sand probably absorbs sunlight and helps speed the defrosting of each sand dune.  This picture was taken by MGS MOC on July 21, 1999. The dunes are located in the south polar region and are expected to be completely defrosted by November or December 1999. North is approximately up, and sunlight illuminates the scene from the upper left. The 500 meter scale bar equals 547 yards; the 300 meter scale is also 328 yards.  http://photojournal.jpl.nasa.gov/catalog/PIA02300',
    thumb: "https://images-assets.nasa.gov/image/PIA02300/PIA02300~thumb.jpg",
  },
  {
    nasaId: "PIA02670",
    title: "Patagonia Glacier, Chile",
    date: "2001-07-21T19:29:58Z",
    center: "JPL",
    description:
      "This ASTER image was acquired on May 2, 2000 over the North Patagonia Ice Sheet, Chile near latitude 47 degrees south, longitude 73 degrees west. The image covers 36 x 30 km. The false color composite displays vegetation in red. The image dramatically shows a single large glacier, covered with crevasses. A semi-circular terminal moraine indicates that the glacier was once more extensive than at present. ASTER data are being acquired over hundreds of glaciers worldwide to measure their changes over time. Since glaciers are sensitive indicators of warming or cooling, this program can provide global data set critical to understand climate change.  This image is located at 46.5 degrees south latitude and 73.9 degrees west longitude.   http://photojournal.jpl.nasa.gov/catalog/PIA02670",
    thumb: "https://images-assets.nasa.gov/image/PIA02670/PIA02670~thumb.jpg",
  },
] as NasaSearchResult[];
